### ISSUE TITLE
Should "document outline" be in title case instead?

### ISSUE THREAD

**Issue by jawwad** [raywenderlich/english-style-guide#1]
Xcode refers to the "document outline" in title case both when you hover over the button in the storyboard and in the "Editor" menu. Should **document outline** be updated to **Document Outline**?

![document-outline2](https://cloud.githubusercontent.com/assets/202240/8818883/7cb44d1a-3014-11e5-8302-f69bdadd4bdb.png)

![document-outline](https://cloud.githubusercontent.com/assets/202240/8818869/547778b8-3014-11e5-96d8-2ee59540f5eb.png)

**Comment by greystar93** [comment]
Doesn't Xcode capitalize everything in these menus?

I know it's confusing, and sometimes I just want to give in and capitalize everything the same way Xcode does, but there's a danger of excess and readability here. My criteria for nouns is generally two-fold: 

(1) Does Apple capitalize the term in its documentation? Often Apple's use is inconsistent, in which case we have to make a judgment call. 

(2) For judgment calls or cases where we have strong grounds for disagreement with Apple's use, is the term something relatively generic, like a single instance of an infinite set (image view, button, etc), or is it something that is both proprietary and of which there is only a single instance (Interface Builder, Auto Layout)? Some terms feel tricky because of the question of whether they are proprietary, and document outline is one of these. Others are the editors (e.g. assistance editor), project navigator and Object Library. I think these terms are more open to debate and sometimes my decisions feel arbitrary and I just want to throw up my hands and capitalize them all.

I think "document outline" is more generic and not very proprietary, hence my decision, but please, argue otherwise!

**Comment by greystar93** [comment]
According to these rules, should "Podfile" really be capitalized, or is it more generic because it's one of an infinite set? Would you say, "the podfile", just as you would, "the glance"?

**Comment by crispy8888** [comment]
I'd say if you're referring to the menu item (as in "click Hide Document Outline") then it's caps. Otherwise, leave it lower-cased in the general sense (as in "Where did my document outline go? Oh right, I hid it earlier.")

If it seems to be an edge case, such as something that very rarely appears in RW publications and is inconsistent across Apple docs, then my approach is to make sure I use it consistently in a particular piece of work as best as possible and realize that a vanishingly small portion of readers will really care deeply about such details across the whole RW.com ecosystem.

**Comment by jawwad** [comment]
I searched a bit and it looks like apple refers to the "document outline" as "outline view" when talking about it...

"If the outline view doesn’t appear, display it by clicking the Show Document Outline control in the lower-left corner of the canvas."
From: https://developer.apple.com/library/mac/recipes/xcode_help-IB_objects_media/Chapters/set_object_delegate.html

"toggle the dock to the outline view, if necessary, by clicking the Show Document Outline control"
From: https://developer.apple.com/library/ios/recipes/xcode_help-IB_objects_media/Chapters/select_object.html

Maybe we can encapsulate this into a recommendation? When referring to the "document outline" prefer referring to it using the term "outline view"? 

Search of developer.apple.com for both terms:
https://www.google.com/search?q=site%3Adeveloper.apple.com+"document+outline"+"outline+view"

Regarding "the podfile" or "the Podfile" it looks like cocoapods.org capitalizes Podfile...
https://www.google.com/search?q=site%3Acocoapods.org+"the+podfile"

**Comment by greystar93** [comment]
@jawwad If we did use "outline view" instead of "document outline," is it possible that a reader might not understand, since the Xcode menu has it as the latter?

Re: Podfile. Some people love to capitalize things. Like the Germans. But if CocoaPods does it, I suppose we should, too.

**Comment by jawwad** [comment]
That's a good point, document outline does seem more specific than outline view even though Apple uses outline view in their docs. Though from the context the reader will probably infer what outline views is pretty quickly. Maybe both are ok? Should it be bolded when it is referred to? Look at the **document outline** or look at the document outline ?

**Comment by greystar93** [comment]
If you think either document outline or outline view are OK, then I do too. 

As for bolding, you Xcode users would know best. I would say probably? I don't bold project navigator, but I do bold the inspectors. I can't remember if I bold the various editors... I think my decisions are based on a sense of whether it's important to call out the thing for the reader's eye, weighed against a desire to avoid too much bolding. The project navigator seems so ubiquitous.
