### ISSUE TITLE
Editor/Inspector Capitalization

### ISSUE THREAD

**Issue by Paradox927** [raywenderlich/english-style-guide#8]
Just wondering about this:  
"**editors** Use lowercase; e.g. assistant editor, standard editor, scene editor."

"**inspectors** Capitalize when referring to a specific inspector in Xcode; e.g., Attributes Inspector, Identity Inspector."

I feel like these two not only contradict one another, but also go against what Apple is doing. Especially when (in the Xcode menus) they are essentially swapped. In Xcode, they read: Assistant Editor and Attributes inspector, respectively. Personally, I think they both should be capitalized. Just my two and a half cents.

**Comment by jawwad** [comment]
Regarding the inspectors, it seems like apple mostly uses a lowercase i for inspector even though they capitalize the first word. "Attributes inspector". 

Based on this google search:
https://www.google.com/search?q=site%3Aapple.com+%22attributes+inspector%22

**Comment by frosty** [comment]
What a coincidence - I just raised a very similar issue in the RW Slack. **project navigator** is also marked as being lowercase, but it's displayed in Xcode with a capital: **Project navigator** (as are all the other navigators).

I feel like the simplest solution to make all of this consistent would be to just follow Xcode's lead and capitalise it the same way as Xcode?

**Comment by jawwad** [comment]
I like the idea of matching Xcode as well, despite the fact that the lowercase i seems a bit weird to me. The tooltip for "Attributes inspector" also shows a lowercase i.

![attributes_inspector](https://cloud.githubusercontent.com/assets/202240/9208427/5f1b4208-4041-11e5-8efe-74f982965a87.png)

**Comment by frosty** [comment]
Yeah, lowercasing the second word seems weird to me too. If I was writing it off the top of my head, I think I'd capitalise both.

**Comment by greystar93** [comment]
I personally think that both the editors and the inspectors should be lowercase, but it's difficult to buck both Apple docs and Xcode, so we've looked to various Apple materials for guidance. Problem is, Apple's style is inconsistent and weird.

If you want to know my thought process for the original decisions re: what to capitalize, I've written it up below. To get right to the point, though, of all my style guide decisions, I've had the most doubts about the rule to render the editors lowercase. I agree that it's inconsistent with the rule for the inspectors. 

I would be OK with changing the rule for the editors, for the sake of consistency. But before we do so, we should be aware that this will mean all the editors working on books will have to make changes in all the chapters they've already handed off. For me that's something like fifteen chapters. Alternatively, we could ask the FPEs to make the changes. I wonder if we should wait until after this latest cycle of books is over.

As for the project navigator, as far as I've seen, Apple's Developer Docs exclusively use lowercase. Apple's Style Guide (yes, there is one) doesn't address the term.

--

For the inspectors, In the developer docs, I've seen both Attributes inspector and Attributes Inspector. I don't believe I've ever seen it all lowercase. Apple's style guide says to use "Attributes inspector," and as you guys pointed out, that's how it is in Xcode. Personally, that mix just bugs me and doesn't seem to accord with any intuitive capitalization use in English, which is why I've said to capitalize the inspectors. We don't always follow Apple.

As for the editors, that's a little trickier. In the developer docs I've seen all three iterations: assistant editor, Assistant Editor and Assistant editor. Apple's style guide stipulates "Assistant Editor." I decided to go with all lowercase instead for these reasons:

* I think authors have a tendency to capitalize _way_ too many terms in tutorials/books. If it's capitalized onscreen, authors tend to write it the same way, which is understandable, but not always necessary. Too many capitalized words makes for ugly text and awkward reading, just like too much bolding.
* The fact that something is capitalized in a menu onscreen isn't by itself a reason to capitalize it in text. Generally speaking, _everything_ in menus is capitalized.
* To me, anything that's referred to using an article is a candidate for being lowercase; e.g., "the label," "the document outline," "the main editor." Something that doesn't take an article, like Interface Builder, should most definitely be capitalized.
* I thought at the time I made made these rules that the inspectors sounded more like proprietary tools and the editors more like generic features. This might not hold water; remember, I don't use Xcode and have to rely on Apple materials and my years of seeing the terms in countless tutorials.

**Comment by greystar93** [comment]
We're going to revisit this after the current book cycle, and for now, stick with the rules as they are.

**Comment by rcritz** [comment]
It’s time to revisit this. I think we need to treat Xcode itself as canon because it’s what the reader actually sees. It reminds me a bit of the episode from the second season of The Next Generation where Dr. Pulaski keeps calling Data “Dah-tah”. After he corrects her for the nth time, she finally asks what’s the difference. He responds, “One is my name; the other is not”. If ee cummings could get away without capitalization, Apple certainly can choose its own rules for how things are named.

**Comment by crispy8888** [comment]
The Apple style guide is actually canon here, and lo and behold the latest ASG actually recommends that we lowercase "inspector" in this instance. We’ll perform an overhaul of our style guide after the current round of books are out. Thanks for raising this @rcritz
